### ISSUE TITLE
Engine metrics scraped on wrong port

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-scaling#107]
We get a lot of `HTTP: Read error : Last write time for /usr/local/Client/metrics failed: LastWriteTimeException /usr/local/Client/metrics failed: boost::filesystem::last_write_time: No such file or directory: "/usr/local/Client/metrics": No such file or directory` entries right now which is caused by something trying to scrape engine `/metrics` on port 9076, instead of the 9090 metrics port.

**Comment by FredrikFolkesson** [comment]
So we are looking for metrics on both 9076 and 9090? (since scaling seems to be working)

**Comment by peol** [comment]
Possibly. Something seems to be scraping the wrong port, not sure which :)
