### ISSUE TITLE
Issue running ./run.sh deploy

### ISSUE THREAD

**Issue by carlioth** [qlik-oss/core-scaling#111]
After the cluster has been created and the doc seed should be done we get the following error: 

```
Waiting for deployment to run
error: unable to upgrade connection: container not found ("nfs-server")
```

**Comment by FredrikFolkesson** [comment]
I can not duplicate this, it works fine when I create my cluster.

**Comment by FredrikFolkesson** [comment]
Closing this since I can not duplicate it.
