### ISSUE TITLE
Downscaling of Machines does not seem to happen

### ISSUE THREAD

**Issue by FredrikFolkesson** [qlik-oss/core-scaling#52]
When putting some load I can see that the pods and machines are scaled up. When removing the load the pods are scaled down but the machines are still up

**Comment by carlioth** [comment]
I've tried to reproduce this scenario. Deployed, added load, machines scaled out, removed load, and it scaled in again. 
Reading about this it would be interesting to see what you would get if you've run the following command: 
`kubectl describe -n kube-system configmap cluster-autoscaler-status`

Most likely it's a pod that can't be evicted. Here is a good write up of possible scenarios: 
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-nodes-with-low-utilization-but-they-are-not-scaled-down-why

**Comment by FredrikFolkesson** [comment]
Closing this since I can not reproduce it either and the downscaling works as it should.
