### ISSUE TITLE
HPA killing pods without pre-hook being executed

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/core-scaling#73]
When scaling down a cluster it seems like the pre-hook is not always being executed on all nodes before being terminated. This problem was seen when doing some load testing on a 8-node cluster in GKE.

The problem occured when the load was decreasing, and a `TERMINATING` flag was put on one of the engine nodes. The pre-hook kicked in and the node stayed alive as long as there were sessions on that node. However the HPA tried to scale down once more during this period, and then two more engine nodes were killed instantly without receiving any `TERMINATING` flag. This would lead to a lot of sessions being killed without having a grace period.

This might be a problem with the HPA logic, but needs to investigate if we can mitigate the problem or file a bug on HPA.

**Comment by sublibra** [comment]
WON'T DO: Repository archived
