### ISSUE TITLE
Update yamls to follow k8s recommendations

### ISSUE THREAD

**Issue by carlioth** [qlik-oss/core-scaling#96]
Running the tool zegl/kube-score will print a list of recommendations / best practices. 
Evaluate and make changes acordingly. 
Output when checking the Qlik-core yamls: 

<img width="797" alt="screen shot 2018-12-02 at 11 12 51" src="https://user-images.githubusercontent.com/908670/49338590-4e22ec80-f623-11e8-943d-01510bef4d25.png">

**Comment by sublibra** [comment]
WON'T DO: Repository archived
